import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import PrelineScript from "@/components/PrelineScript";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Albert Car Rental",
  description: "Generated by Fernando Aponte",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>

      <PrelineScript />
    </html>
  );
}
